name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  SERVICE: pvc-pro

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --image gcr.io/$PROJECT_ID/$SERVICE \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars "CASHFREE_APP_ID=${{ secrets.CASHFREE_APP_ID }}" \
          --set-env-vars "CASHFREE_SECRET_KEY=${{ secrets.CASHFREE_SECRET_KEY }}" \
          --set-env-vars "CASHFREE_WEBHOOK_SECRET=${{ secrets.CASHFREE_WEBHOOK_SECRET }}" \
          --set-env-vars "FIREBASE_PROJECT_ID=pvc-pro-web" \
          --set-env-vars "FIREBASE_CREDENTIAL_PATH=/secrets/firebase/firebase-adminsdk.json" \
          --update-secrets firebase-adminsdk=/secrets/firebase/firebase-adminsdk.json:latest \
          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
